/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by `scripts/generate-tokens.mjs` from the `:root` block of
 * `css/tokens.css`. After editing that file, regenerate this one with:
 *
 *   node scripts/generate-tokens.mjs
 *
 * …and commit the result. This file is checked in rather than built on
 * the fly, so a token rename shows up in the PR diff and `tsc`/editor
 * IntelliSense work on a clean clone without running a build step first.
 */

/** Colour tokens — surfaces, text, borders and semantic intents, all oklch(). */
export type KairoColorToken =
  | '--kairo-background'
  | '--kairo-foreground'
  | '--kairo-card'
  | '--kairo-card-foreground'
  | '--kairo-popover'
  | '--kairo-popover-foreground'
  | '--kairo-muted'
  | '--kairo-muted-foreground'
  | '--kairo-primary'
  | '--kairo-primary-foreground'
  | '--kairo-secondary'
  | '--kairo-secondary-foreground'
  | '--kairo-accent'
  | '--kairo-accent-foreground'
  | '--kairo-success'
  | '--kairo-success-foreground'
  | '--kairo-warning'
  | '--kairo-warning-foreground'
  | '--kairo-danger'
  | '--kairo-danger-foreground'
  | '--kairo-border'
  | '--kairo-input'
  | '--kairo-ring';

/** Corner-radius tokens. */
export type KairoRadiusToken =
  | '--kairo-radius'
  | '--kairo-radius-sm'
  | '--kairo-radius-md'
  | '--kairo-radius-lg'
  | '--kairo-radius-full';

/** Border and focus-ring line-weight tokens (as opposed to their colors, which are `KairoColorToken`). */
export type KairoStructuralToken =
  | '--kairo-border-width'
  | '--kairo-ring-width'
  | '--kairo-ring-offset';

/** Font-stack and line-height tokens. */
export type KairoTypographyToken =
  | '--kairo-font-sans'
  | '--kairo-font-mono'
  | '--kairo-leading-tight'
  | '--kairo-leading-normal'
  | '--kairo-leading-relaxed';

/** Box-shadow tokens (color channel, strength multiplier and the composed shadows). */
export type KairoShadowToken =
  | '--kairo-shadow-color'
  | '--kairo-shadow-strength'
  | '--kairo-shadow-sm'
  | '--kairo-shadow-md'
  | '--kairo-shadow-lg';

/** Transition-duration and easing-curve tokens. */
export type KairoMotionToken =
  | '--kairo-duration-fast'
  | '--kairo-duration-normal'
  | '--kairo-duration-slow'
  | '--kairo-ease-standard'
  | '--kairo-ease-emphasized'
  | '--kairo-ease-out';

/** Every Kairo design token, as the CSS custom property name it is declared under. */
export type KairoToken =
  | KairoColorToken
  | KairoRadiusToken
  | KairoStructuralToken
  | KairoTypographyToken
  | KairoShadowToken
  | KairoMotionToken;

/** Every token name, in `:root`'s declaration order. See `KairoToken` for the typed union. */
export const KAIRO_TOKENS: readonly KairoToken[] = [
  '--kairo-background',
  '--kairo-foreground',
  '--kairo-card',
  '--kairo-card-foreground',
  '--kairo-popover',
  '--kairo-popover-foreground',
  '--kairo-muted',
  '--kairo-muted-foreground',
  '--kairo-primary',
  '--kairo-primary-foreground',
  '--kairo-secondary',
  '--kairo-secondary-foreground',
  '--kairo-accent',
  '--kairo-accent-foreground',
  '--kairo-success',
  '--kairo-success-foreground',
  '--kairo-warning',
  '--kairo-warning-foreground',
  '--kairo-danger',
  '--kairo-danger-foreground',
  '--kairo-border',
  '--kairo-input',
  '--kairo-ring',
  '--kairo-radius',
  '--kairo-radius-sm',
  '--kairo-radius-md',
  '--kairo-radius-lg',
  '--kairo-radius-full',
  '--kairo-border-width',
  '--kairo-ring-width',
  '--kairo-ring-offset',
  '--kairo-font-sans',
  '--kairo-font-mono',
  '--kairo-leading-tight',
  '--kairo-leading-normal',
  '--kairo-leading-relaxed',
  '--kairo-shadow-color',
  '--kairo-shadow-strength',
  '--kairo-shadow-sm',
  '--kairo-shadow-md',
  '--kairo-shadow-lg',
  '--kairo-duration-fast',
  '--kairo-duration-normal',
  '--kairo-duration-slow',
  '--kairo-ease-standard',
  '--kairo-ease-emphasized',
  '--kairo-ease-out',
];

/** Returns the `var(--kairo-…)` reference for a token, e.g. `token('--kairo-primary')` -> `"var(--kairo-primary)"`. */
export function token(name: KairoToken): string {
  return `var(${name})`;
}
