import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/accordion/index.ts',
    'src/alert-dialog/index.ts',
    'src/avatar/index.ts',
    'src/badge/index.ts',
    'src/button/index.ts',
    'src/card/index.ts',
    'src/checkbox/index.ts',
    'src/collapsible/index.ts',
    'src/combobox/index.ts',
    'src/context-menu/index.ts',
    'src/dialog/index.ts',
    'src/drawer/index.ts',
    'src/i18n/index.ts',
    'src/input/index.ts',
    'src/menu/index.ts',
    'src/meter/index.ts',
    'src/number-field/index.ts',
    'src/popover/index.ts',
    'src/progress/index.ts',
    'src/radio-group/index.ts',
    'src/select/index.ts',
    'src/separator/index.ts',
    'src/slider/index.ts',
    'src/spinner/index.ts',
    'src/switch/index.ts',
    'src/tabs/index.ts',
    'src/toast/index.ts',
    'src/toggle-group/index.ts',
    'src/tooltip/index.ts',
  ],
  format: ['esm'],
  unbundle: true,
  dts: true,
});
